name: TWSE/TPEX AfterMarket API On GitHub Action
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 7:00 AM UTC (3:00 PM Taipei time)
jobs:
  API:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install -r requirements.txt

      - name: Running TWSE-PERatio.py
        run: |
          python TWSE-PERatio.py || true
          python TPEX-PERatio.py || true
          # python csv-merge.py || true
          csvstack TWSE.csv TPEX.csv | csvcut -c 證券代號,證券名稱,收盤價,殖利率(%),股利年度,本益比,股價淨值比, 財報年/季,每股股利(註)  > TWSE_TPEX1.csv || trur
      - name: Lines count
        run: |
          python CountCSVLine.py TWSE.json TWSE.csv "TWSE Total Company"
          python CountCSVLine.py TPEX.json TPEX.csv "TPEX Total Company"
          python CountCSVLine.py TWSE_TPEX.Json TWSE_TPEX.csv "TWSE+TPEX Total Company"

      - name: Commit and Push The Results From Python Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git add *.csv 
         git add *.json
         git commit -m "⬆️ GitHub Actions Results added" || true
         git push || true
