name: TWSE/TPEX AfterMarket API On GitHub Action
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 7:00 AM UTC (3:00 PM Taipei time)
jobs:
  API:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install -r requirements.txt

      - name: Running TWSE-PERatio.py
        run: |
          python TWSE-PERatio.py || true
          python TPEX-PERatio.py || true
          python csv-merge.py || true

      - name: Commit and Push The Results From Python Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git add *.csv 
         git commit -m "GitHub Actions Results added"
         git push
